#!/bin/sh

rm -f inst/bin/execdde.exe
rm -f inst/bin/execdde.txt
rm -f inst/bin/SystemFonts.exe
rm -f inst/bin/SystemFonts.txt
rm -R -f inst/bin

rm -R -f inst/tklibs/tile0.7.2
rm -R -f inst/tklibs/Tktable2.9
rm -R -f inst/tklibs/winico0.6